### ISSUE TITLE
Sendmail option

### ISSUE THREAD

**Issue by passbe** [jhuckaby/pixl-mail#2]
Am looking to use sendmail with Cronicle, and see the underlying nodemailer does support this:

https://nodemailer.com/transports/sendmail/

Would this be possible to change in pixl-mail then subsequently in Cronicle?

**Comment by jhuckaby** [comment]
You should be able to do this with Cronicle right now.  Just add a `mail_options` object in your configuration file, and set these 3 properties within:

```js
"mail_options": {
    "sendmail": true,
    "newline": "unix",
    "path": "/usr/sbin/sendmail"
}
```

I'll update the docs for both pixl-mail and Cronicle so this is made clear.

Thanks!

**Comment by passbe** [comment]
Ah this explains it. Thank you very much for your quick response.
