### ISSUE TITLE
update nodemailer version

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-mail#3]
This is related to 
https://github.com/jhuckaby/Cronicle/issues/404

please update nodemailer to the latest version to fix vulnerabilities reported by npm 
https://npmjs.com/advisories/1708

**Comment by jhuckaby** [comment]
Ah yes, thank you, I forgot about this one.  Will do this tonight.  

Thanks!

**Comment by jhuckaby** [comment]
Fixed in v1.0.11, thanks!
